//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by BLToolkit template for T4.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

using BLToolkit.Data;
using BLToolkit.Data.Linq;
using BLToolkit.DataAccess;
using BLToolkit.Mapping;
using BLToolkit.Validation;

using CQRS.Common;

using Economy.DataAccess.BlToolkit.Entities;

namespace Economy.DataAccess.BlToolkit.DbManagers
{
    internal partial class EconomyDb
    {
        public Table<BankEntity> BankTable { get { return this.GetTable<BankEntity>(); } }
        public Table<CourseArhiveEntity> CourseArhiveTable { get { return this.GetTable<CourseArhiveEntity>(); } }
        public Table<CurrencyTypeEntity> CurrencyTypeTable { get { return this.GetTable<CurrencyTypeEntity>(); } }
        public Table<MontlyReportEntity> MontlyReportTable { get { return this.GetTable<MontlyReportEntity>(); } }
        public Table<SystemUserEntity> SystemUserTable { get { return this.GetTable<SystemUserEntity>(); } }
        public Table<TransactionEntity> TransactionTable { get { return this.GetTable<TransactionEntity>(); } }
        public Table<WalletEntity> WalletTable { get { return this.GetTable<WalletEntity>(); } }
    }

    [TableName(Database = "economy", Owner = "public", Name = "\"Bank\"")]
    internal partial class BankBaseEntity : BaseEntity
    {
        [MapField("\"Id\""), Identity, PrimaryKey(1), Required]
        public virtual Int32 Id { get; set; } // integer

        [MapField("\"Name\""), Required]
        public virtual String Name { get; set; } // character varying

    }

    [TableName(Database = "economy", Owner = "public", Name = "\"CourseArhive\"")]
    internal partial class CourseArhiveBaseEntity : BaseEntity
    {
        [MapField("\"CurrencyTypeId\""), Required]
        public virtual Int32 CurrencyTypeId { get; set; } // integer

        [MapField("\"RegDate\""), Required]
        public virtual DateTime RegDate { get; set; } // timestamp with time zone

        [MapField("\"Buy\""), Required]
        public virtual Double Buy { get; set; } // double precision

        [MapField("\"Sel\""), Required]
        public virtual Double Sel { get; set; } // double precision

        [MapField("\"CurrencyTypeBaseId\""), Required]
        public virtual Int32 CurrencyTypeBaseId { get; set; } // integer

        [MapField("\"BankId\""), PrimaryKey(6), Required]
        public virtual Int32 BankId { get; set; } // integer


        // fk_coursearhive_currencytype
        [Association(ThisKey = "\"CurrencyTypeId\"", OtherKey = "\"Id\"", CanBeNull = false)]
        public virtual CurrencyTypeEntity CurrencyType
         { get; set; }
        // fk_coursearhive_currencytypebase
        [Association(ThisKey = "\"CurrencyTypeBaseId\"", OtherKey = "\"Id\"", CanBeNull = false)]
        public virtual CurrencyTypeEntity CurrencyTypeBase
         { get; set; }
        // fk_coursearhive_bank
        [Association(ThisKey = "\"BankId\"", OtherKey = "\"Id\"", CanBeNull = false)]
        public virtual BankEntity Bank
         { get; set; }}

    [TableName(Database = "economy", Owner = "public", Name = "\"CurrencyType\"")]
    internal partial class CurrencyTypeBaseEntity : BaseEntity
    {
        [MapField("\"Id\""), Identity, PrimaryKey(1), Required]
        public virtual Int32 Id { get; set; } // integer

        [MapField("\"Name\""), Required]
        public virtual String Name { get; set; } // character varying

        [MapField("\"ShortName\""), Required]
        public virtual String ShortName { get; set; } // character varying(3)(3)

    }

    [TableName(Database = "economy", Owner = "public", Name = "\"MontlyReport\"")]
    internal partial class MontlyReportBaseEntity : BaseEntity
    {
        [MapField("\"Id\""), PrimaryKey(1), Required]
        public virtual Guid Id { get; set; } // uuid

        [MapField("\"StartBalance\""), Nullable]
        public virtual Decimal? StartBalance { get; set; } // money

        [MapField("\"EndBalance\""), Nullable]
        public virtual Decimal? EndBalance { get; set; } // money

        [MapField("\"StartDate\""), Required]
        public virtual DateTime StartDate { get; set; } // timestamp without time zone

        [MapField("\"WalletId\""), Required]
        public virtual Guid WalletId { get; set; } // uuid


        // pk_montlyreport_wallet
        [Association(ThisKey = "\"WalletId\"", OtherKey = "\"Id\"", CanBeNull = false)]
        public virtual WalletEntity Wallet
         { get; set; }}

    [TableName(Database = "economy", Owner = "public", Name = "\"SystemUser\"")]
    internal partial class SystemUserBaseEntity : BaseEntity
    {
        [MapField("\"Id\""), PrimaryKey(1), Required]
        public virtual Guid Id { get; set; } // uuid

        [MapField("\"Name\""), Required]
        public virtual String Name { get; set; } // character varying

    }

    [TableName(Database = "economy", Owner = "public", Name = "\"Transaction\"")]
    internal partial class TransactionBaseEntity : BaseEntity
    {
        [MapField("\"Id\""), PrimaryKey(1), Required]
        public virtual Guid Id { get; set; } // uuid

        [MapField("\"RegistrationDate\""), Required]
        public virtual DateTime RegistrationDate { get; set; } // timestamp without time zone

        [MapField("\"TransactionDate\""), Nullable]
        public virtual DateTime? TransactionDate { get; set; } // timestamp without time zone

        [MapField("\"Code\""), Required]
        public virtual String Code { get; set; } // character varying

        [MapField("\"Description\""), Required]
        public virtual String Description { get; set; } // character varying

        [MapField("\"CurrencyTypeId\""), Required]
        public virtual Int32 CurrencyTypeId { get; set; } // integer

        [MapField("\"QuantityByTransaction\""), Required]
        public virtual Decimal QuantityByTransaction { get; set; } // money

        [MapField("\"QuantityByWallet\""), Nullable]
        public virtual Decimal? QuantityByWallet { get; set; } // money

        [MapField("\"Commission\""), Nullable]
        public virtual Decimal? Commission { get; set; } // money

        [MapField("\"FromWalletId\""), Nullable]
        public virtual Guid? FromWalletId { get; set; } // uuid

        [MapField("\"ToWalletId\""), Required]
        public virtual Guid ToWalletId { get; set; } // uuid

        [MapField("\"MontlyReportId\""), Nullable]
        public virtual Guid? MontlyReportId { get; set; } // uuid


        // fk_transaction_currency
        [Association(ThisKey = "\"CurrencyTypeId\"", OtherKey = "\"Id\"", CanBeNull = false)]
        public virtual CurrencyTypeEntity CurrencyType
         { get; set; }
        // fk_transaction_montly_report
        [Association(ThisKey = "\"MontlyReportId\"", OtherKey = "\"Id\"", CanBeNull = true)]
        public virtual MontlyReportEntity MontlyReport
         { get; set; }
        // fk_transactionfromwallet_wallet
        [Association(ThisKey = "\"FromWalletId\"", OtherKey = "\"Id\"", CanBeNull = true)]
        public virtual WalletEntity FromWallet
         { get; set; }
        // fk_transactiontowallet_wallet
        [Association(ThisKey = "\"ToWalletId\"", OtherKey = "\"Id\"", CanBeNull = false)]
        public virtual WalletEntity ToWallet
         { get; set; }}

    [TableName(Database = "economy", Owner = "public", Name = "\"Wallet\"")]
    internal partial class WalletBaseEntity : BaseEntity
    {
        [MapField("\"Id\""), PrimaryKey(1), Required]
        public virtual Guid Id { get; set; } // uuid

        [MapField("\"Name\""), Required]
        public virtual String Name { get; set; } // character varying

        [MapField("\"StartBalance\""), Nullable]
        public virtual Decimal? StartBalance { get; set; } // money

        [MapField("\"Balance\""), Nullable]
        public virtual Decimal? Balance { get; set; } // money

        [MapField("\"SystemUserId\""), Nullable]
        public virtual Guid? SystemUserId { get; set; } // uuid

        [MapField("\"CurrencyTypeId\""), Required]
        public virtual Int32 CurrencyTypeId { get; set; } // integer


        // fk_wallet_currencytype
        [Association(ThisKey = "\"CurrencyTypeId\"", OtherKey = "\"Id\"", CanBeNull = false)]
        public virtual CurrencyTypeEntity CurrencyType
         { get; set; }
        // fk_wallet_systemuser
        [Association(ThisKey = "\"SystemUserId\"", OtherKey = "\"Id\"", CanBeNull = true)]
        public virtual SystemUserEntity SystemUser
         { get; set; }}
}
