//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by BLToolkit template for T4.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

using BLToolkit.Data;
using BLToolkit.Data.Linq;
using BLToolkit.DataAccess;
using BLToolkit.Mapping;
using BLToolkit.Validation;

using CQRS.Common;

using Economy.DataAccess.BlToolkit.Entities;

namespace Economy.DataAccess.BlToolkit.DbManagers
{
    internal partial class EconomyDb
    {
        public Table<BankEntity> BankTable { get { return this.GetTable<BankEntity>(); } }
        public Table<CourseArhiveEntity> CourseArhiveTable { get { return this.GetTable<CourseArhiveEntity>(); } }
        public Table<CurrencyTypeEntity> CurrencyTypeTable { get { return this.GetTable<CurrencyTypeEntity>(); } }
        public Table<MontlyReportEntity> MontlyReportTable { get { return this.GetTable<MontlyReportEntity>(); } }
        public Table<SystemUserEntity> SystemUserTable { get { return this.GetTable<SystemUserEntity>(); } }
        public Table<TransactionEntity> TransactionTable { get { return this.GetTable<TransactionEntity>(); } }
        public Table<WalletEntity> WalletTable { get { return this.GetTable<WalletEntity>(); } }
    }

    [TableName(Database = "economy", Owner = "public", Name = "\"Bank\"")]
    internal partial class BankEntity : BaseEntity
    {
        [MapField("\"Id\""), Identity, PrimaryKey(1), Required]
        public Int32 Id { get; set; } // integer

        [MapField("\"Name\""), Required]
        public String Name { get; set; } // character varying

    }

    [TableName(Database = "economy", Owner = "public", Name = "\"CourseArhive\"")]
    internal partial class CourseArhiveEntity : BaseEntity
    {
        [MapField("\"CurrencyTypeId\""), Required]
        public Int32 CurrencyTypeId { get; set; } // integer

        [MapField("\"RegDate\""), Required]
        public DateTime RegDate { get; set; } // timestamp with time zone

        [MapField("\"Buy\""), Required]
        public Double Buy { get; set; } // double precision

        [MapField("\"Sel\""), Required]
        public Double Sel { get; set; } // double precision

        [MapField("\"CurrencyTypeBaseId\""), Required]
        public Int32 CurrencyTypeBaseId { get; set; } // integer

        [MapField("\"BankId\""), PrimaryKey(6), Required]
        public Int32 BankId { get; set; } // integer


        // fk_coursearhive_currencytype
        [Association(ThisKey = "\"CurrencyTypeId\"", OtherKey = "\"Id\"", CanBeNull = false)]
        public CurrencyTypeEntity fkcoursearhivecurrencytype { get; set; }

        // fk_coursearhive_currencytypebase
        [Association(ThisKey = "\"CurrencyTypeBaseId\"", OtherKey = "\"Id\"", CanBeNull = false)]
        public CurrencyTypeEntity fkcoursearhivecurrencytypebase { get; set; }

        // fk_coursearhive_bank
        [Association(ThisKey = "\"BankId\"", OtherKey = "\"Id\"", CanBeNull = false)]
        public BankEntity fkcoursearhivebank { get; set; }
    }

    [TableName(Database = "economy", Owner = "public", Name = "\"CurrencyType\"")]
    internal partial class CurrencyTypeEntity : BaseEntity
    {
        [MapField("\"Id\""), Identity, PrimaryKey(1)]
        public Int32 Id { get; set; } // integer

        [MapField("\"Name\"")]
        public String Name { get; set; } // character varying

        [MapField("\"ShortName\"")]
        public String ShortName { get; set; } // character varying(3)(3)

    }

    [TableName(Database = "economy", Owner = "public", Name = "\"MontlyReport\"")]
    internal partial class MontlyReportEntity : BaseEntity
    {
        [MapField("\"Id\""), PrimaryKey(1), Required]
        public Guid Id { get; set; } // uuid

        [MapField("\"StartBalance\""), Nullable]
        public Decimal? StartBalance { get; set; } // money

        [MapField("\"EndBalance\""), Nullable]
        public Decimal? EndBalance { get; set; } // money

        [MapField("\"StartDate\""), Required]
        public DateTime StartDate { get; set; } // timestamp without time zone

        [MapField("\"WalletId\""), Required]
        public Guid WalletId { get; set; } // uuid


        // pk_montlyreport_wallet
        [Association(ThisKey = "\"WalletId\"", OtherKey = "\"Id\"", CanBeNull = false)]
        public WalletEntity pkmontlyreportwallet { get; set; }
    }

    [TableName(Database = "economy", Owner = "public", Name = "\"SystemUser\"")]
    internal partial class SystemUserEntity : BaseEntity
    {
        [MapField("\"Id\""), PrimaryKey(1), Required]
        public Guid Id { get; set; } // uuid

        [MapField("\"Name\""), Required]
        public String Name { get; set; } // character varying

    }

    [TableName(Database = "economy", Owner = "public", Name = "\"Transaction\"")]
    internal partial class TransactionEntity : BaseEntity
    {
        [MapField("\"Id\""), PrimaryKey(1), Required]
        public Guid Id { get; set; } // uuid

        [MapField("\"RegistrationDate\""), Required]
        public DateTime RegistrationDate { get; set; } // timestamp without time zone

        [MapField("\"TransactionDate\""), Nullable]
        public DateTime? TransactionDate { get; set; } // timestamp without time zone

        [MapField("\"Code\""), Required]
        public String Code { get; set; } // character varying

        [MapField("\"Description\""), Required]
        public String Description { get; set; } // character varying

        [MapField("\"CurrencyTypeId\""), Required]
        public Int32 CurrencyTypeId { get; set; } // integer

        [MapField("\"QuantityByTransaction\""), Required]
        public Decimal QuantityByTransaction { get; set; } // money

        [MapField("\"QuantityByWallet\""), Nullable]
        public Decimal? QuantityByWallet { get; set; } // money

        [MapField("\"Commission\""), Nullable]
        public Decimal? Commission { get; set; } // money

        [MapField("\"FromWalletId\""), Nullable]
        public Guid? FromWalletId { get; set; } // uuid

        [MapField("\"ToWalletId\""), Required]
        public Guid ToWalletId { get; set; } // uuid

        [MapField("\"MontlyReportId\""), Nullable]
        public Guid? MontlyReportId { get; set; } // uuid


        // fk_transaction_currency
        [Association(ThisKey = "\"CurrencyTypeId\"", OtherKey = "\"Id\"", CanBeNull = false)]
        public CurrencyTypeEntity fktransactioncurrency { get; set; }

        // fk_transaction_montly_report
        [Association(ThisKey = "\"MontlyReportId\"", OtherKey = "\"Id\"", CanBeNull = true)]
        public MontlyReportEntity fktransactionmontlyreport { get; set; }

        // fk_transactionfromwallet_wallet
        [Association(ThisKey = "\"FromWalletId\"", OtherKey = "\"Id\"", CanBeNull = true)]
        public WalletEntity fktransactionfromwalletwallet { get; set; }

        // fk_transactiontowallet_wallet
        [Association(ThisKey = "\"ToWalletId\"", OtherKey = "\"Id\"", CanBeNull = false)]
        public WalletEntity fktransactiontowalletwallet { get; set; }
    }

    [TableName(Database = "economy", Owner = "public", Name = "\"Wallet\"")]
    internal partial class WalletEntity : BaseEntity
    {
        [MapField("\"Id\""), PrimaryKey(1), Required]
        public Guid Id { get; set; } // uuid

        [MapField("\"Name\""), Required]
        public String Name { get; set; } // character varying

        [MapField("\"StartBalance\""), Nullable]
        public Decimal? StartBalance { get; set; } // money

        [MapField("\"Balance\""), Nullable]
        public Decimal? Balance { get; set; } // money

        [MapField("\"SystemUserId\""), Nullable]
        public Guid? SystemUserId { get; set; } // uuid

        [MapField("\"CurrencyTypeId\""), Required]
        public Int32 CurrencyTypeId { get; set; } // integer


        // fk_wallet_currencytype
        [Association(ThisKey = "\"CurrencyTypeId\"", OtherKey = "\"Id\"", CanBeNull = false)]
        public CurrencyTypeEntity fkwalletcurrencytype { get; set; }

        // fk_wallet_systemuser
        [Association(ThisKey = "\"SystemUserId\"", OtherKey = "\"Id\"", CanBeNull = true)]
        public SystemUserEntity fkwalletsystemuser { get; set; }
    }
}
