//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by BLToolkit template for T4.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
/*

internal partial class BankBaseDto : BaseDto{
    public Int32 Id { get; set; }

    public String Name { get; set; }

}

internal partial class CourseArhiveBaseDto : BaseDto{
    public Int32 CurrencyTypeId { get; set; }

    public DateTime RegDate { get; set; }

    public Double Buy { get; set; }

    public Double Sel { get; set; }

    public Int32 CurrencyTypeBaseId { get; set; }

    public Int32 BankId { get; set; }

}

internal partial class CurrencyTypeBaseDto : BaseDto{
    public Int32 Id { get; set; }

    public String Name { get; set; }

    public String ShortName { get; set; }

}

internal partial class MontlyReportBaseDto : BaseDto{
    public Guid Id { get; set; }

    public Decimal? StartBalance { get; set; }

    public Decimal? EndBalance { get; set; }

    public DateTime StartDate { get; set; }

    public Guid WalletId { get; set; }

}

internal partial class SystemUserBaseDto : BaseDto{
    public Guid Id { get; set; }

    public String Name { get; set; }

}

internal partial class TransactionBaseDto : BaseDto{
    public Guid Id { get; set; }

    public DateTime RegistrationDate { get; set; }

    public DateTime? TransactionDate { get; set; }

    public String Code { get; set; }

    public String Description { get; set; }

    public Int32 CurrencyTypeId { get; set; }

    public Decimal QuantityByTransaction { get; set; }

    public Decimal? QuantityByWallet { get; set; }

    public Decimal? Commission { get; set; }

    public Guid? FromWalletId { get; set; }

    public Guid ToWalletId { get; set; }

    public Guid? MontlyReportId { get; set; }

}

internal partial class WalletBaseDto : BaseDto{
    public Guid Id { get; set; }

    public String Name { get; set; }

    public Decimal? StartBalance { get; set; }

    public Decimal? Balance { get; set; }

    public Guid? SystemUserId { get; set; }

    public Int32 CurrencyTypeId { get; set; }

}
*/
